include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = PillVolumePrefs
PillVolumePrefs_FILES = PVRootListController.m
PillVolumePrefs_FRAMEWORKS = UIKit
PillVolumePrefs_PRIVATE_FRAMEWORKS = Preferences
PillVolumePrefs_INSTALL_PATH = /Library/PreferenceBundles
PillVolumePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
